project:
  type: website

website:
  title: project-final-team 2
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-F25/final-project-team-2 # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: team2presentation.ipynb
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
